import { createFileRoute } from '@tanstack/react-router';
import { ArrowDown, ArrowUpRight, ArrowUp, Github, Linkedin, Code2, Cloud, Blocks, Sparkles, Check, GitBranch } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Navigation } from '@/components/portfolio/navigation';
import { ProjectBlock, Status } from '@/components/portfolio/project';
import { Contact } from '@/components/portfolio/contact';
import { projects, socialLinks } from '@/data/projects';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Paul Olutunmbi — Student. Developer. Building forward.' },
    { name: 'description', content: 'Olutunmbi Paul Oreoluwa is a Computer Science student at LAUTECH building full-stack JavaScript, AI, cloud and Web3 products. Explore his work and engineering journey.' },
    { property: 'og:title', content: 'Paul Olutunmbi — Full-stack, Cloud & Web3' },
    { property: 'og:description', content: 'Real products. An honest student journey. Explore NOMI, Crypto-Vault, Glimpse and the work of Paul Olutunmbi, a LAUTECH Computer Science student.' },
    { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
  ] }), pendingComponent: PortfolioLoading, component: Portfolio,
});
function PortfolioLoading() {
  return <div className="container" aria-busy="true" aria-label="Loading portfolio"><div className="hero"><div className="skeleton-line h-4 w-48" /><div className="skeleton-line mt-8 h-24 w-full" /><div className="skeleton-line mt-4 h-24 w-3/4" /><div className="skeleton-line mt-8 h-12 w-1/2" /></div></div>;
}
const domains = [
  { title: 'Application engineering', Icon: Code2, level: 'BUILT WITH / EXPERIENCED WITH', skills: ['JavaScript', 'React', 'Node.js', 'Express', 'MongoDB', 'Firebase / Firestore', 'REST APIs', 'JWT / session authentication', 'Firebase Auth', 'Socket.IO', 'Tailwind', 'Git / GitHub'] },
  { title: 'Cloud & DevOps', Icon: Cloud, level: 'WORKING KNOWLEDGE', skills: ['Azure VMs / VNet / Storage / NSGs / App Service', 'Azure DevOps', 'CI/CD', 'Docker', 'Terraform', 'Ansible', 'Linux / Ubuntu', 'WSL', 'Nginx', 'DNS', 'SSH', 'Kubernetes · Minikube lab level'] },
  { title: 'Web3 development', Icon: Blocks, level: 'BUILT WITH / CONTINUING TO LEARN', skills: ['Solidity', 'Hardhat', 'Ethers.js', 'OpenZeppelin', 'Ethereum', 'Sepolia', 'Wallet integration'] },
  { title: 'AI-powered workflows', Icon: Sparkles, level: 'BUILT WITH / EXPERIENCED WITH', skills: ['AI APIs', 'Groq', 'Google Gemini APIs', 'AI intent pipelines', 'AI-powered workflows'] },
];
const journey = [
  ['01', 'Self-learning Python', 'My starting point in late 2024.'],
  ['02', 'Full-stack web development', 'Frontend, backend, APIs, databases and authentication.'],
  ['03', 'Web3 / Smart contracts', 'Solidity, wallets and on-chain application logic.'],
  ['04', 'AI integrations', 'AI-powered products and safe action workflows.'],
  ['05', 'Cloud / DevOps', 'Learning to deploy, operate and understand infrastructure.'],
];
function Label({ number, name, right }: { number: string; name: string; right: string }) { return <div className="section-label"><span>{number} / {name}</span><span>{right}</span></div>; }
function Portfolio() {
  return <><Navigation /><main><div className="container"><section className="hero reveal" aria-labelledby="hero-title"><div className="eyebrow"><span className="eyebrow-dot" />PAUL OLUTUNMBI <span>/</span> DEVHUMBLE3</div><h1 className="hero-heading" id="hero-title">Computer Science student <br />building <em>full-stack, cloud</em> <br />and Web3 products<span className="text-primary">.</span></h1><div className="hero-bottom"><div><p className="hero-description">I build practical software across full-stack development, AI integrations, cloud infrastructure and blockchain.</p><div className="hero-actions"><Button asChild><a href="#work">View projects <ArrowDown /></a></Button><Button asChild variant="ghost"><a href={socialLinks.github} target="_blank" rel="noreferrer"><Github />GitHub</a></Button><Button asChild variant="ghost"><a href={socialLinks.linkedin} target="_blank" rel="noreferrer"><Linkedin />LinkedIn</a></Button><Button asChild variant="ghost"><a href="#contact">Contact <ArrowUpRight /></a></Button></div></div><div className="hero-location mono"><strong>300 Level · LAUTECH · Nigeria</strong>LEARNING DEEPLY. BUILDING PRACTICALLY.</div></div><div className="progression-strip"><span className="progress-label">THE JOURNEY SO FAR</span>{['Python', 'Full-stack web', 'Web3 / Contracts', 'AI integrations', 'Cloud / DevOps'].map((step,i) => <span key={step} className="contents"><b>{step}</b>{i < 4 && <span className="progress-arrow">→</span>}</span>)}</div><p className="mobile-student-line mono">300 Level · LAUTECH · Nigeria</p></section>
      <section id="work" className="section"><Label number="01" name="SELECTED WORK" right="IDEAS → WORKING SOFTWARE" /><div className="section-heading"><h2>Selected projects.</h2><p>A selection of real products, experiments and the technical decisions behind them.</p></div>{projects.filter(p => p.tier === 1).map((project,index) => <div key={project.id}><ProjectBlock project={project} index={index} /><div className="project-progression"><GitBranch size={13} />{project.progression}</div></div>)}<div className="secondary-projects">{projects.filter(p => p.tier === 2).map((project,index) => <div key={project.id}><ProjectBlock project={project} index={index+3} /><div className="project-progression"><GitBranch size={13} />{project.progression}</div></div>)}</div><div className="where-started"><p className="small-label mono">WHERE IT STARTED</p>{projects.filter(p => p.tier === 3).map(project => <ProjectBlock key={project.id} project={project} index={5} />)}</div><div className="also-built"><span className="mono">ALSO BUILT</span><h3>EventNest <ArrowUpRight className="inline" size={15} /></h3><p>An event / dinner platform for the LAUTECH Computer Science dinner, with Paystack, QR-based features and voting. <strong>Roughly 813 transactions recorded.</strong></p></div></section></div>
      <div className="band"><section className="section container" id="about"><Label number="02" name="ABOUT" right="A STUDENT. A BUILDER. STILL GROWING." /><div className="about-grid"><div><h2>I started with what<br />you can see.<br />Now I’m learning<br /><em>what makes it work.</em></h2></div><div className="about-copy"><p>I’m <strong>Olutunmbi Paul Oreoluwa</strong> — Paul Olutunmbi online, sometimes “Humble.” I’m a 300-level Computer Science student at LAUTECH, with an expected graduation in 2028.</p><p>I began teaching myself Python in late 2024. Around September 2025, development became a serious, deliberate journey: from complete frontend interfaces to APIs, databases, authentication, media and realtime systems.</p><p>After full-stack web development, I moved into Web3 and smart contracts, learning how wallets and on-chain rules change an application’s trust model. Then came AI integrations: building NOMI meant working with external APIs and explicit approval workflows. Now cloud and DevOps are teaching me how software is deployed and operated.</p><p><strong>The focus now is becoming a stronger engineer</strong> — someone who understands the infrastructure and systems beneath the application layer, not just the interface on top.</p><div className="education-note mono"><span>B.SC. COMPUTER SCIENCE<br />LADOKE AKINTOLA UNIVERSITY OF TECHNOLOGY</span><span>EXPECTED<br />2028</span></div></div></div><div className="journey">{journey.map(([number,title,text]) => <div className="journey-step" key={number}><span className="mono">{number}</span><h4>{title}</h4><p>{text}</p></div>)}</div></section></div>
      <div className="container"><section className="section" id="engineering"><Label number="03" name="ENGINEERING" right="TOOLS WITH CONTEXT, NOT PERCENTAGES" /><div className="section-heading"><h2>Tools I work with.</h2><p>Strongest in full-stack JavaScript. Expanding into the systems that support it.</p></div><div className="engineering-grid">{domains.map(({title,Icon,level,skills}) => <div className="engineering-domain" key={title}><div className="domain-heading"><Icon /><h3>{title}</h3></div><p className="domain-level mono">{level}</p><div className="skills-list">{skills.map(skill => <span key={skill}>{skill}</span>)}</div></div>)}</div><div className="developing"><div><h3>Currently developing</h3><Status status="IN PROGRESS" /></div><div className="skills-list">{['TypeScript', 'Advanced backend engineering', 'Cloud architecture', 'CI/CD', 'Infrastructure as Code', 'Kubernetes', 'Blockchain infrastructure', 'AI × software engineering'].map(skill => <span key={skill}>{skill}</span>)}</div></div></section>
      <section className="section" id="experience"><Label number="04" name="EXPERIENCE" right="PRACTICE, NOT PRETENSE" /><div className="section-heading"><h2>Experience & learning labs.</h2><p>Internships, learning labs and client-facing products.</p></div><div className="experience-list"><div className="experience-row"><div className="experience-date mono">FROM 27 JUL 2026<br />3-MONTH PLACEMENT<br /><Status status="IN PROGRESS" /></div><div><h3>Ibadan Digital Academy</h3><h4>SIWES / Software & Computer Science Intern</h4><p>Learned and practiced Azure fundamentals, VMs, networking, Storage, NSGs, Terraform, Ansible, Docker, WSL / Ubuntu, Linux, Azure DevOps, CI/CD, Git / GitHub / Azure Repos and Node.js deployment. Also worked as a frontend developer on the company’s website and facilitated frontend development classes for students.</p></div></div><div className="experience-row"><div className="experience-date mono">CLIENT / PRODUCT WORK</div><div><h3>Products outside the classroom</h3><h4>Aminat Studio · EventNest</h4><p>A public artist portfolio with a protected CMS, and an event platform for the LAUTECH Computer Science dinner.</p></div></div></div><div className="labs-grid"><div className="lab"><span className="mono">LEARNING LAB / AZURE DEVOPS</span><h4>A tested path to deployment</h4><p>Node.js on Azure App Service via Azure Repos and Azure Pipelines. Workload identity federation; automated Jest and Supertest tests run before deployment.</p></div><div className="lab"><span className="mono">LEARNING LAB / KUBERNETES</span><h4>Understanding what runs underneath</h4><p>Minikube with Docker on Windows. Created a deployment, scaled 1 → 3 → 5 replicas, exposed it via NodePort, observed pod replacement and used rollout history. Lab experience, not production Kubernetes.</p></div></div></section>
      <section className="section" id="community"><Label number="05" name="LEADERSHIP & COMMUNITY" right="GROWING WITH PEOPLE" /><div className="section-heading"><h2>Leadership & community.</h2></div><div className="community-grid"><div className="community-list"><h3>ROLES & PARTICIPATION</h3>{[['Cowrywise Ambassador','Accepted'],['Course Representative',''],['ACOMS','Incoming Assistant General Secretary']].map(([title,note]) => <div className="community-item" key={title}><div><h4>{title}</h4>{note && <small>{note}</small>}</div><Check aria-label="Confirmed role or participation" /></div>)}</div></div></section>
      <section className="section" id="learning"><Label number="06" name="LEARNING & CERTIFICATIONS" right="THE WORK IS NOT FINISHED" /><div className="section-heading"><h2>Learning & certifications.</h2></div><div className="learning-row"><span className="mono">MAY — NOV 2025</span><div><h3>DSA / Digital Skillup Africa — Software Development</h3><p>Software planning and design, and full-stack development. Certificate of completion issued November 2025.</p></div><Status status="COMPLETED" /></div><div className="learning-row"><span className="mono">SEP 2025 — APR 2026</span><div><h3>SQI — MERN / Full-Stack programme</h3><p>Certificate pending.</p></div><span className="mono">CERTIFICATE PENDING</span></div><div className="learning-row"><span className="mono">CURRENTLY LEARNING</span><div><h3>Azure / cloud & DevOps, Kubernetes, TypeScript and Web3 development</h3><p>Deepening my foundation through practical study and labs.</p></div><Status status="IN PROGRESS" /></div><div className="exploration"><Status status="EXPLORING" note="IDEA, NOT A BUILT PROJECT" /><h3>An AI-powered multi-chain wallet analyzer</h3><p>Exploring an idea for understanding transaction history, token movements and wallet activity patterns across chains. Still an idea — not a completed product.</p></div></section><Contact /></div></main><div className="container"><footer className="site-footer"><p>Olutunmbi Paul Oreoluwa · Computer Science, LAUTECH · Built to keep growing.</p><span className="footer-meta"><a href="#">BACK TO TOP <ArrowUp size={12} /></a></span></footer></div></>;
}
